# PROFILE ID'S:
  # FreeSpace2 = 13302
  # Mouse Tracker = 8501
profile_ID = 13302

[default_padding]
left = 3
right = 3
top = 0
bottom = 0

[display0]
left = -160.00
right = -80.00
top = -16.00
bottom = -55.00

[display1]
left = -63.00
right = 63.00
top = 28.35
bottom = -28.35