# Notes:
#   - Will crash if display bound values are not floats
#     (need to make sure each follows format: "\d+\.\d+")
#
#
# PROFILE ID'S:
  # FreeSpace2 = 13302
  # Aerofly = 2025

[general]
watchdog_enabled = true
TrackIR_DLL_directory = "default" # Specify "default" to get value from registry or an absolute path eg. "C:\Program Files..."
profile = 1

[default_padding]
left = 3
right = 3
top = 0
bottom = 0

[profiles]

  [profiles.1]
  profile_ID = 13302

  # Desktop Dual Monitor Setup
  [profiles.1.display.0]
  left = -43.00
  right = 50.00
  top = 19.00
  bottom = -19.00

  [profiles.1.display.1]
  left = 62.00
  right = 180.00
  top = 19.00
  bottom = -19.00

  [profiles.2]
  profile_ID = 2025

  # Laptop Monitor
  [profiles.2.display.0]
  left = -50.00
  right = 50.00
  top = 32.00
  bottom = -32.00

  [profiles.3]
  profile_ID = 2025

  [profiles.3.display.0]
  left = -25.00
  right = 25.00
  top = 15.00
  bottom = -15.00