# PROFILE ID'S:
# FreeSpace2 = 13302
# Aerofly = 2025


[General]
track_on_start = false
quit_on_loss_of_track_ir = true
watchdog_enabled = false
# Specify "default" to get value from registry or an absolute path eg. "C:\Program Files..."
trackir_dll_directory = "default"
active_profile = "Desktop Dual Monitor"

[[Profiles]]
profile_id = 13302
name = "Desktop Dual Monitor"
use_default_padding = true

# Desktop Dual Monitor Setup
[[Profiles.DisplayMappings]]
left = -43
right = 50
top = 19
bottom = -19
[[Profiles.DisplayMappings]]
left = 62
right = 180
top = 19
bottom = -19

[[Profiles]]
name = "Desktop Single Monitor"
profile_id = 2025
use_default_padding = true

[[Profiles.DisplayMappings]]
left = -50
right = 50
top = 32
bottom = -32

[[Profiles]]
name = "Laptop"
profile_id = 2025
use_default_padding = true

[[Profiles.DisplayMappings]]
left = -21.00
right = 21.00
top = 15.00
bottom = -15.00


[DefaultPadding]
left = 3
right = 3
top = 0
bottom = 0